pipeline {
    agent any

    environment {
        DOCKERHUB_USER = "alisha64"
        VERSION = "v${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }


        stage('Run Tests') {
            steps {
                echo 'Running tests...'
                sh 'echo "Tests completed"'
            }
        }

        stage('Security Scan') {
            steps {
                sh '''
                if command -v trivy >/dev/null 2>&1; then
                    trivy fs .
                else
                    echo "Trivy not installed"
                fi
                '''
            }
        }

        stage('Build Docker Images') {
            steps {
                sh '''
                docker build -t ${DOCKERHUB_USER}/devops-backend:${VERSION} app/backend
                docker build -t ${DOCKERHUB_USER}/devops-frontend:${VERSION} app/frontend

                docker tag ${DOCKERHUB_USER}/devops-backend:${VERSION} ${DOCKERHUB_USER}/devops-backend:latest
                docker tag ${DOCKERHUB_USER}/devops-frontend:${VERSION} ${DOCKERHUB_USER}/devops-frontend:latest
                '''
            }
        }

        stage('Push Images') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                    docker push ${DOCKERHUB_USER}/devops-backend:${VERSION}
                    docker push ${DOCKERHUB_USER}/devops-backend:latest

                    docker push ${DOCKERHUB_USER}/devops-frontend:${VERSION}
                    docker push ${DOCKERHUB_USER}/devops-frontend:latest
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                echo "Deployment stage ready"
                '''
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully"
        }

        failure {
            echo "Pipeline failed"
        }
    }
}
