apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  db_host: "database-service"
  db_port: "5432"
  db_name: "devopsdb"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  db_password: "postgres123"
  db_user: "postgres"
